source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.4'
use_frameworks!

target 'TastingRoomDelMar' do 
	pod 'Parse'
	pod 'ParseUI'
	pod 'ParseCrashReporting'
	pod 'ParseFacebookUtilsV4', '~> 1.8.5'
	pod 'FBSDKCoreKit'
	pod 'FBSDKLoginKit'
	pod 'FBSDKShareKit'
	pod 'Alamofire', '3.1.1'
	pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
	pod 'SwiftValidator', '3.0.1'
	pod 'PureLayout'
	pod 'Stripe'
	pod 'ENSwiftSideMenu', '~> 0.1'
	pod 'Bolts'
	pod 'Bond', '~> 4.0'
	pod 'RxSwift', '~> 2.0'
	pod 'RxCocoa', '~> 2.0'
	pod 'RxBlocking', '~> 2.0'
	pod 'Fabric'
	pod 'Crashlytics'		
end
